# Generated by Django 2.2.6 on 2020-01-08 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sex', models.CharField(choices=[('P', 'Prefer not to say'), ('F', 'Female'), ('M', 'Male'), ('NB', 'Non-Binary')], default='P', max_length=18)),
                ('interestedIn', models.CharField(choices=[('1', 'Anything that eats'), ('2', 'Men'), ('3', 'Women'), ('4', 'Men and Women'), ('5', 'Non-Binary')], default=('1', 'Anything that eats'), max_length=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
