# Generated by Django 2.2.6 on 2020-01-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favCuisine', models.CharField(max_length=35)),
                ('taste', models.CharField(choices=[('1', 'Sweet'), ('2', 'Savory'), ('3', 'Both')], default=('3', 'Both'), max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='eater',
            name='age',
            field=models.CharField(default=18, max_length=2),
        ),
    ]
