# Generated by Django 2.2.6 on 2020-01-08 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200108_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eater',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
