# Generated by Django 2.2.6 on 2020-01-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200109_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinterests',
            name='leastFavCuisine',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
