# Generated by Django 2.2.6 on 2020-01-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200109_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eater',
            name='location',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='eater',
            name='sex',
            field=models.CharField(choices=[('P', 'Prefer not to say'), ('F', 'Female'), ('M', 'Male'), ('NB', 'Non-Binary')], default='P', max_length=17),
        ),
    ]
