# Generated by Django 2.2.6 on 2020-01-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200109_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topFavCuisine', models.CharField(blank=True, max_length=35, null=True)),
                ('secFavCuisine', models.CharField(blank=True, max_length=35, null=True)),
                ('thirdFavCuisine', models.CharField(blank=True, max_length=35, null=True)),
                ('leastFavCuisine', models.CharField(blank=True, max_length=35, null=True)),
                ('taste', models.CharField(choices=[('1', 'Sweet'), ('2', 'Savory'), ('3', 'Both')], default=('3', 'Both'), max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='eater',
            name='leastFavCuisine',
        ),
        migrations.RemoveField(
            model_name='eater',
            name='secFavCuisine',
        ),
        migrations.RemoveField(
            model_name='eater',
            name='taste',
        ),
        migrations.RemoveField(
            model_name='eater',
            name='thirdFavCuisine',
        ),
        migrations.RemoveField(
            model_name='eater',
            name='topFavCuisine',
        ),
    ]
