# Generated by Django 2.2.6 on 2020-01-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200109_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('about_my_date', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eater',
            name='leastFavCuisine',
        ),
        migrations.RemoveField(
            model_name='eater',
            name='secFavCuisine',
        ),
        migrations.RemoveField(
            model_name='eater',
            name='thirdFavCuisine',
        ),
        migrations.RemoveField(
            model_name='eater',
            name='topFavCuisine',
        ),
        migrations.AddField(
            model_name='eater',
            name='least_fav_cuisine',
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='eater',
            name='sec_fav_cuisine',
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='eater',
            name='third_fav_cuisine',
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='eater',
            name='top_fav_cuisine',
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='eater',
            name='location',
            field=models.TextField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='eater',
            name='taste',
            field=models.TextField(choices=[('1', 'Sweet'), ('2', 'Savory'), ('3', 'Both')], default=('3', 'Both'), max_length=6),
        ),
    ]
