# Generated by Django 2.2.6 on 2020-01-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200109_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eater',
            name='least_fav_cuisine',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='eater',
            name='location',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='eater',
            name='sec_fav_cuisine',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='eater',
            name='third_fav_cuisine',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='eater',
            name='top_fav_cuisine',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
