# Generated by Django 2.2.6 on 2020-01-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20200109_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eater',
            old_name='least_fav_cuisine',
            new_name='least',
        ),
        migrations.RenameField(
            model_name='eater',
            old_name='sec_fav_cuisine',
            new_name='sec',
        ),
        migrations.RenameField(
            model_name='eater',
            old_name='third_fav_cuisine',
            new_name='third',
        ),
        migrations.RenameField(
            model_name='eater',
            old_name='top_fav_cuisine',
            new_name='top',
        ),
    ]
