# Generated by Django 2.2.6 on 2020-01-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_remove_eater_taste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eater',
            old_name='interestedIn',
            new_name='interested_in',
        ),
    ]
