# Generated by Django 2.2.6 on 2020-01-09 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20200109_0249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
